config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :clients
  resources :billing_plans
  resources :subscriptions
  get 'client/subscriptions' => 'clients#subscriptions'
  get 'ConfirmSuscription' => 'subscriptions#execute'
  post 'paypal_webhook' => 'webhooks#paypal_webhook'
  post '/' => 'webhooks#paypal_webhook'
  get 'webhooks' => 'webhooks#index'
  get 'webhook/new' => 'webhooks#create'
  delete 'webhook' => 'webhooks#destroy'
  root :to => "welcome#index"
end

app/models/billing_plan.rb
class BillingPlan < ApplicationRecord
end

app/controllers/billing_plans_controller.rb
include PayPal::SDK::REST
class BillingPlansController < ApplicationController
  def current_client
    @client
  end
  def index
    @billing_plans = BillingPlan.all
    if params[:client]
      @client = Client.find(params[:client])
    end
  end
  def new
    @billing_plan = BillingPlan.new
    @billing_plan.name = ''
  end
  def create
    @billing_plan = BillingPlan.new(billing_plan_params)
    if @billing_plan.save
        @plan = Plan.new({
          :name => @billing_plan.name,
          :description => @billing_plan.description,
          :type => "INFINITE",
          :payment_definitions => [
              {
                  :name => "Regular Payments",
                  :type => "REGULAR",
                  :frequency => "MONTH",
                  :frequency_interval => "1",
                  :amount => {
                      :value => @billing_plan.amount,
                      :currency => @billing_plan.currency
                  },
                  :cycles => "0"
              }
          ],

          :merchant_preferences => {
              :setup_fee => {
                  :value => "3",
                  :currency => "USD"
              },
              :return_url => "https://0b4bd5dd.ngrok.io/ConfirmSuscription",
              :cancel_url => "https://0b4bd5dd.ngrok.io",
              :auto_bill_amount => "YES",
              :initial_fail_amount_action => "CONTINUE",
              :max_fail_attempts => "3"
          }
        })

      if params[:trial]
        @plan.payment_definitions.push({
          :name => "Regular Payments",
          :type => "TRIAL",
          :frequency => @billing_plan.trial_period,
          :frequency_interval => "1",
          :amount => {
            :value => 0,
            :currency => @billing_plan.currency
          },
          :cycles => "1"
        })

      end
       # Create plan
      if @plan.create
        logger.info "Plan creado: #{@plan.id}"
        # Plan update activation object
        plan_update = {
          :op => 'replace',
          :path => '/',
          :value => {
            :state => 'ACTIVE'
          }
        }
        @billing_plan.update_attribute(:plan_id, @plan.id)
        # Activate plan
        if @plan and @plan.update(plan_update)
          puts("Billing plan activated with ID [#{@plan.id}]")
          logger.info "Billing plan was activated: #{@plan.id}"
        else
          logger.error  @plan.error.inspect
        end
      else
        logger.error  @plan.error.inspect
      end
      redirect_to billing_plans_path
    else
      render 'new'
    end
  end

  def destroy
    @billing_plan = BillingPlan.find(params[:id])

    if @billing_plan.plan_id
      plan_update = {
        :op => 'replace',
        :path => '/',
        :value => {
        :state => 'DELETED'
        }
      }
      @plan = Plan.find(@billing_plan.plan_id)
      @plan.update(plan_update)
    end
    @billing_plan.destroy
    redirect_to billing_plans_path
  end

  private
  def billing_plan_params
    params.require(:billing_plan).permit(:name, :description, :amount, :currency, :trial, :trial_period, :plan_id, :client_id)
  end
end

app/helpers/billing_plans_helper.rb
module BillingPlansHelper
end

app/views/billing_plans/index.html.erb
<div class= "container">
<%= link_to 'back', clients_path, class: 'pull-right' %>
<div class="row">
  <% @billing_plans.each do |plan| %>
    <div class="col-xs-6 col-sm-4 col-md-2">
      <div class="panel panel-info">
        <div class="panel-heading"><strong><%= plan.name %></strong>
           <%= link_to 'X', billing_plan_path(plan), method: :delete, data: { confirm: 'Are you sure?' }, class: 'pull-right' %>
        </div>

        <div class="panel-body">
          <p><%= plan.description %></p>
          <span class="pull-right badge">$<%= plan.amount %></span>
          <%= image_tag "logo_home.png", class: 'center-block', width: "40px", height: "40px" %>
        </div>
        <div class="panel-footer text-center">
          <%= link_to raw("<img src='https://www.sandbox.paypal.com/en_US/i/btn/btn_subscribe_LG.gif' alt='PayPal - The safer, easier way to pay online!'>"),
          new_subscription_path(plan: plan, client: @client) , data: { "disable-with": "Loading .." } %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= link_to 'Create a plan', new_billing_plan_path %><br>

app/views/billing_plans/new.html.erb
<div class="container">
<%= simple_form_for( @billing_plan, html: { class: 'container-fluid well horizontal-form' } ) do |f| %>
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1 ">
      <p class="lead text-center">Subscription Creation</p>
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :amount, label:"Monthly cost" %>
      <%= f.input :currency, collection: ["USD"] %>
      <%= f.input :trial %>
      <%= f.input :trial_period, collection: ["DAY","WEEK","MONTH"] %>
      <div class="text-center">
        <%= f.button :submit, "Create",
         "data-toggle" => "tooltip", class: "btn btn-success",  data: { "disable-with": "Loading .." } %>
      </div>
    </div>
  </div>
<% end %>
</div>