config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :clients
  resources :billing_plans
  resources :subscriptions
  get 'client/subscriptions' => 'clients#subscriptions'
  get 'ConfirmSuscription' => 'subscriptions#execute'
  post 'paypal_webhook' => 'webhooks#paypal_webhook'
  post '/' => 'webhooks#paypal_webhook'
  get 'webhooks' => 'webhooks#index'
  get 'webhook/new' => 'webhooks#create'
  delete 'webhook' => 'webhooks#destroy'
  root :to => "welcome#index"
end

app/models/client.rb
class Client < ApplicationRecord
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
    @clients = Client.all
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)

    if @client.save
      redirect_to clients_path
    else
      render 'new'
    end
  end
  def destroy
    @client = Client.find(params[:id])
    @client.destroy
    redirect_to clients_path
  end
  private def client_params
    params.require(:client).permit(:first_name, :last_name, :street, :city, :state, :email, :postal_code, :country_code, :credit_card_id)
  end

  def subscriptions
    @client_subscriptions = Subscription.where(client_id: params[:client] )
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/index.html.erb
<div class= "container">


<table class="table table-striped">
    <tr>
        <th>name</th>
        <th>description</th>
        <th>email</th>
        <th>street</th>
        <th></th>
        <th></th>
    </tr>
  <% @clients.each do |client| %>
    <tr>
      <td>
        <%= client.first_name %>
      </td>
      <td>
        <%= client.country_code %>
      </td>
      <td>
        <%= client.email %>
      </td>
      <td>
        <%= client.street %>
      </td>
      <td>
        <%= link_to 'Delete', client_path(client),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>

      </td>
      <td>
          <%= link_to 'Login', billing_plans_path(client: client) %>
      </td>
      <td>
          <%= link_to 'See all my subscriptions', client_subscriptions_path(client: client) %>
      </td>
    <tr>
  <% end %>
</table>


<%= link_to 'Create a client', new_client_path %>
<%= link_to 'Back', root_path %>

app/views/clients/new.html.erb
<div class="container">
<%= simple_form_for( @client, html: { class: 'container-fluid well horizontal-form' })  do |f| %>
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1 ">
      <p class="lead text-center">Subscription Creation</p>
      <%= f.input :first_name %>
      <%= f.input :last_name %>
      <%= f.input :email, placeholder: 'Enter email' %>
      <%= f.input :state, collection: [ "NK", "CA","OH"] %>
      <%= f.input :city, placeholder: 'New york' %>
      <%= f.input :street %>
      <%= f.input :postal_code %>
      <%= f.country_select :country_code, class: "dropdown" %>
      <div class="text-center">
        <%= f.button :submit, "Create", :method => :post, data: { "disable-with": "..." },
         "data-toggle" => "tooltip", class: "btn btn-success" %>
      </div>
    </div>
  </div>
<% end %>
</div>

app/views/clients/subscriptions.html.erb
<div class= "container">


<table class="table table-striped">
    <tr>
        <th>plan</th>
        <th>client</th>
        <th>payment_method</th>
        <th>agreement_id</th>
    </tr>
  <% @client_subscriptions.each do |subscription| %>
    <tr>
      <td>
        <%= subscription.plan_id %>
      </td>
      <td>
        <%= subscription.client_id %>
      </td>
      <td>
        <%= subscription.payment_method %>
      </td>
      <td>
        <%= subscription.agreement_id %>
      </td>
      <td>
        <%= link_to 'Delete', subscription_path(subscription),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
      </td>
    <tr>
  <% end %>
</table>
</div>